### ISSUE TITLE
ENOENT: no such file or directory

### ISSUE THREAD

**Issue by GoalTV** [OscarXcore/twitch-mass-ban#6]
I'm getting this error on Windows & Linux whenever I try to run this tool

(node:15372) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at TwitchMassBan.parseListFlag (/home/hoobs/twitch-mass-ban/index.js:117:19)
    at TwitchMassBan.process (/home/hoobs/twitch-mass-ban/index.js:126:25)
    at /home/hoobs/twitch-mass-ban/index.js:76:22
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15372) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15372) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Error using --unhandled-rejections=strict

Error: ENOENT: no such file or directory, open
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at TwitchMassBan.parseListFlag (/home/hoobs/twitch-mass-ban/index.js:117:19)
    at TwitchMassBan.process (/home/hoobs/twitch-mass-ban/index.js:126:25)
    at /home/hoobs/twitch-mass-ban/index.js:76:22
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT'
}

And error with --trace-warnings

(node:15823) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at TwitchMassBan.parseListFlag (/home/hoobs/twitch-mass-ban/index.js:117:19)
    at TwitchMassBan.process (/home/hoobs/twitch-mass-ban/index.js:126:25)
    at /home/hoobs/twitch-mass-ban/index.js:76:22
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
(node:15823) Error: ENOENT: no such file or directory, open
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at TwitchMassBan.parseListFlag (/home/hoobs/twitch-mass-ban/index.js:117:19)
    at TwitchMassBan.process (/home/hoobs/twitch-mass-ban/index.js:126:25)
    at /home/hoobs/twitch-mass-ban/index.js:76:22
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:15823) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)

**Comment by GoalTV** [comment]
Actually seems like I downloaded wrong version instead clone from git I downloaded from release and works now.
